# FROM node:19-alpine


# COPY package.json /app/
# COPY src /app/

# WORKDIR /app

# RUN npm install

# CMD ["node", "server.js"]

# this file in the blueprint for building an image
# need to use the docker build command

FROM node:19-alpine

ENV MONGO_DB_USERNAME=admin \
    MONGO_DB_PWD=password

RUN mkdir -p /home/producer

COPY ./producer /home/producer

CMD ["node", "/home/producer/src/server.js"]
